# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "centos/7"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
  config.vm.define "kube-master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "kube-master"
    subconfig.vm.network :private_network, ip: "192.168.100.10"
  end
  
  (1..NODE_COUNT).each do |i|
    config.vm.define "kube-node-#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "kube-node-#{i}"
      subconfig.vm.network :private_network, ip: "192.168.100.#{i + 10}"
    end
  end

end
